### ISSUE TITLE
Can't get the code to work, connects to wifi but not to server.

### ISSUE THREAD

**Issue by WillZad** [CosmicBoris/ESP8266SMTP#2]
Hopefully you have time to take a look at this. Not sure what I've done wrong.
Here is the setup, with email addys and PW changed.

void setup()
{
	Serial.begin(115200);
	delay(2000);
	
	connection_state = WiFiConnect(ssid, password);

	if(!connection_state) {  				// if not connected to WIFI
		Awaits(reconnect_interval);         // constantly trying to connect
	}

	uint32_t startTime = millis();
	
	SMTP.setEmail("abcdefg@gmail.com")
		.setPassword("123456789")
		.Subject("ESP8266SMTP Gmail test")
		.setFrom("abcdefg@gmail.com")
		.setForGmail();						// simply sets port to 465 and setServer("smtp.gmail.com");						
													   // message text from http://www.blindtextgenerator.com/lorem-ipsum
	if(SMTP.Send("abcdefg@gmail.com", "The European languages are members of the same family.")) {
		Serial.println(F("Message sent"));
	} else {
		Serial.print(F("Error sending message: "));
		Serial.println(SMTP.getError());
	} 
	
	Serial.println(millis() - startTime);
}

and this is the response from the serial monitor

Connection: ESTABLISHED
Got IP address: 192.168.0.22
Error sending message: Could not connect to mail server
551

Any ideas?
thanks

**Comment by WillZad** [comment]
I uncommented the LOG_LEVEL_2 linein the helper file and got this 

Connection: ESTABLISHED
Got IP address: 192.168.0.22
Connecting to: smtp.gmail.com
Error sending message: Could not connect to mail server
273

and yes, Acces allowed for less secure apps is done in Google.

Not sure if this helps

**Comment by CosmicBoris** [comment]
Just tried myself, not sure why but my code does not work with ESP8266 core
for Arduino version 2.5.0, but is works with version 2.4.2

пн, 18 лют. 2019 о 14:30 WillZad <notifications@github.com> пише:

**Comment by WillZad** [comment]
Yup, works just fine with 2.4.2.
Thanks

**Comment by Martin-Laclaustra** [comment]
@CosmicBoris The reason why it does not work is (most probably) because of the update of _WiFiClientSecure_ to use BearSSL.
I succeeded in making it work with a couple of little hacks.
**First option:**
You solve it just by adding this line after:
https://github.com/CosmicBoris/ESP8266SMTP/blob/bc73ca1219ebc9c0293e775c3181927bc790aa15/src/ESP8266SMTP.cpp#L121
`client.setInsecure();`

**Another option:**
It also works by adding a line after:
https://github.com/CosmicBoris/ESP8266SMTP/blob/bc73ca1219ebc9c0293e775c3181927bc790aa15/src/ESP8266SMTP.cpp#L121
`client.setFingerprint(_fingerprint);`

You need a place to store the _fingerprint in the class (in ESP8266SMTP.h):
`uint8_t _fingerprint[20];`
... and a setter:
```
bool setFingerprint(const uint8_t fingerprint[20]) {
  memcpy_P(_fingerprint, fingerprint, 20);
}
```
The fingerprint is the SHA-1 of the server certificate, and you should provide it when configuring the SMTP object in the host code.

May be you should allow the same range of connection options that are currently offered in:
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h

**Comment by Martin-Laclaustra** [comment]
As you seem to be busy, I took the liberty to create [a repository](https://github.com/Martin-Laclaustra/ESP8266SecureSMTP) from yours and extend the library to the current SSL support.
In the case you want to update yours, please tell me.

**Comment by Etcay15** [comment]
> Yup, works just fine with 2.4.2.
> Thanks

Thank you, It's working fine, with 2.4.2
